name: Review
on: [pull_request]

jobs:
  call-review:
    permissions:
      contents: read
      pull-requests: write
    uses: NilsB44/infra/.github/workflows/reviewer.yml@main
    secrets: inherit
